runtime: go113
service: default

instance_class: F1

env_variables:
    GIN_MODE: release

handlers:
        - url: /.*
          script: auto
          secure: always
          redirect_http_response_code: 301
